Avoid conflicts with terraform and tfenv while upgrading each
A conflict error message on installing `tfenv`:
```
$ brew install tfenv

Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core and homebrew/cask).
==> Updated Formulae
Updated 1 formula.
==> Updated Casks
Updated 5 casks.

==> Downloading https://ghcr.io/v2/homebrew/core/tfenv/manifests/2.2.2
########################################################################
100.0%
==> Downloading
https://ghcr.io/v2/homebrew/core/tfenv/blobs/sha256:bbf7732d73d27dd91579c827b60a55674515a96e1755f2bbf842e78e01c9afc0
==> Downloading from
https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:bbf7732d73d27dd91579c827b60a55674515a96e1755f2bbf842e78e01c9afc0?se=2021-06-17T07%3A40%3A00Z&
########################################################################
100.0%
Error: Cannot install tfenv because conflicting formulae are installed.
  terraform: because tfenv symlinks terraform binaries

  Please `brew unlink terraform` before continuing.

  Unlinking removes a formula's symlinks from /usr/local. You can
  link the formula again after the install finishes. You can --force
  this
  install, but the build may fail or cause obscure side effects in the
  resulting software.
```