Introduce `zlib`
Since it seems that `zlib` bundled with macOS can not be used, install it with "HomeBrew".

Error was:
```
$ pyenv install 3.7.2
python-build: use openssl from homebrew
python-build: use readline from homebrew
Downloading Python-3.7.2.tar.xz...
-> https://www.python.org/ftp/python/3.7.2/Python-3.7.2.tar.xz
Installing Python-3.7.2...
python-build: use readline from homebrew

BUILD FAILED (OS X 10.14.2 using python-build 20180424)

Inspect or clean up the working tree at /var/folders/jc/lfh90w855jn_12kp0pwz6tpw0000gn/T/python-build.20190111153944.39642
Results logged to /var/folders/jc/lfh90w855jn_12kp0pwz6tpw0000gn/T/python-build.20190111153944.39642.log

Last 10 log lines:
  File "/private/var/folders/jc/lfh90w855jn_12kp0pwz6tpw0000gn/T/python-build.20190111153944.39642/Python-3.7.2/Lib/ensurepip/__main__.py", line 5, in <module>
    sys.exit(ensurepip._main())
  File "/private/var/folders/jc/lfh90w855jn_12kp0pwz6tpw0000gn/T/python-build.20190111153944.39642/Python-3.7.2/Lib/ensurepip/__init__.py", line 204, in _main
    default_pip=args.default_pip,
  File "/private/var/folders/jc/lfh90w855jn_12kp0pwz6tpw0000gn/T/python-build.20190111153944.39642/Python-3.7.2/Lib/ensurepip/__init__.py", line 117, in _bootstrap
    return _run_pip(args + [p[0] for p in _PROJECTS], additional_paths)
  File "/private/var/folders/jc/lfh90w855jn_12kp0pwz6tpw0000gn/T/python-build.20190111153944.39642/Python-3.7.2/Lib/ensurepip/__init__.py", line 27, in _run_pip
    import pip._internal
zipimport.ZipImportError: can't decompress data; zlib not available
make: *** [install] Error 1
```