Change the order due to library dependency :metal:
Homebrew said:
> diff-pdf: XQuartz is required to install this formula.X11Requirement unsatisfied!
>
> You can install with Homebrew-Cask:
>   brew cask install xquartz
>
> You can download from:
>   https://xquartz.macosforge.org
> Error: An unsatisfied requirement failed this build.