Looks good without `wireshark-chmodbpf`
I did not have a chance to use `wireshark-chmodbpf` in my environment.
When I installed `wireshark` with "Homebrew Cask", I got an installation error due to conflicts, so I uninstalled it.

Error was:
> Error: Cask 'wireshark-chmodbpf' conflicts with 'wireshark'.