Switch to use the stable version of `neovim` :vim:
It has been felt that development speed is fast and I had been thought that
there are many advantages of using development version compared to stable version.
However, at the time I encountering a build error in the development version after a long time, I reconsidered.
It seems that the features of the stable version are very satisfactory, I think.

Build error was:
```
==> Upgrading neovim
==> Cloning https://github.com/neovim/neovim.git
Cloning into '/Users/machupicchubeta/Library/Caches/Homebrew/neovim--git'...
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
==> Downloading https://luarocks.org/manifests/gvvaughan/lpeg-1.0.1-1.src.rock
######################################################################## 100.0%
==> Downloading https://github.com/libmpack/libmpack-lua/releases/download/1.0.7/libmpack-lua-1.0.7.tar.gz
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws.com/85478740/9fa71720-c5d7-11e7-8570-693a6dc12f44?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWNJYAX4CSVEH53A%2F20190515%2Fus-east-1%2Fs3%2Faws4_r
######################################################################## 100.0%
==> Downloading https://luarocks.org/manifests/kikito/inspect-3.1.1-0.src.rock
######################################################################## 100.0%
==> Downloading https://luarocks.org/manifests/luarocks/luabitop-1.0.2-3.rockspec
######################################################################## 100.0%
==> Downloading https://github.com/LuaDist/luabitop/archive/1.0.2.tar.gz
==> Downloading from https://codeload.github.com/LuaDist/luabitop/tar.gz/1.0.2
######################################################################## 100.0%
==> Downloading https://luarocks.org/luafilesystem-1.7.0-2.src.rock
######################################################################## 100.0%
==> Downloading https://stevedonovan.github.io/files/penlight-1.5.4.zip
######################################################################## 100.0%
==> Downloading https://luarocks.org/lua_cliargs-3.0-1.src.rock
######################################################################## 100.0%
==> Downloading https://github.com/hoelzro/lua-term/archive/0.07.tar.gz
==> Downloading from https://codeload.github.com/hoelzro/lua-term/tar.gz/0.07
######################################################################## 100.0%
==> Downloading https://luarocks.org/luasystem-0.2.1-0.src.rock
######################################################################## 100.0%
==> Downloading https://luarocks.org/dkjson-2.5-2.src.rock
######################################################################## 100.0%
==> Downloading https://github.com/Olivine-Labs/say/archive/v1.3-1.tar.gz
==> Downloading from https://codeload.github.com/Olivine-Labs/say/tar.gz/v1.3-1
######################################################################## 100.0%
==> Downloading https://github.com/Olivine-Labs/luassert/archive/v1.7.10.tar.gz
==> Downloading from https://codeload.github.com/Olivine-Labs/luassert/tar.gz/v1.7.10
######################################################################## 100.0%
==> Downloading https://github.com/Olivine-Labs/mediator_lua/archive/v1.1.2-0.tar.gz
==> Downloading from https://codeload.github.com/Olivine-Labs/mediator_lua/tar.gz/v1.1.2-0
######################################################################## 100.0%
==> Downloading https://github.com/Olivine-Labs/busted/archive/v2.0.rc12-1.tar.gz
==> Downloading from https://codeload.github.com/Olivine-Labs/busted/tar.gz/v2.0.rc12-1
######################################################################## 100.0%
==> Downloading https://luarocks.org/manifests/mpeterv/luacheck-0.21.2-1.src.rock
######################################################################## 100.0%
==> Downloading https://luarocks.org/luv-1.9.1-1.src.rock
######################################################################## 100.0%
==> Downloading https://luarocks.org/coxpcall-1.17.0-1.src.rock
######################################################################## 100.0%
==> Downloading https://github.com/neovim/lua-client/archive/0.1.0-1.tar.gz
==> Downloading from https://codeload.github.com/neovim/lua-client/tar.gz/0.1.0-1
######################################################################## 100.0%
==> luarocks make --lua-dir=/usr/local/opt/lua@5.1 --tree=/private/tmp/neovim-20190515-46477-mw9nvr/deps-build
==> luarocks make --lua-dir=/usr/local/opt/lua@5.1 --tree=/private/tmp/neovim-20190515-46477-mw9nvr/deps-build
==> luarocks make --lua-dir=/usr/local/opt/lua@5.1 --tree=/private/tmp/neovim-20190515-46477-mw9nvr/deps-build
==> luarocks make --lua-dir=/usr/local/opt/lua@5.1 --tree=/private/tmp/neovim-20190515-46477-mw9nvr/deps-build
==> luarocks make --lua-dir=/usr/local/opt/lua@5.1 --tree=/private/tmp/neovim-20190515-46477-mw9nvr/deps-build
==> luarocks make --lua-dir=/usr/local/opt/lua@5.1 --tree=/private/tmp/neovim-20190515-46477-mw9nvr/deps-build
==> luarocks make --lua-dir=/usr/local/opt/lua@5.1 --tree=/private/tmp/neovim-20190515-46477-mw9nvr/deps-build
==> luarocks make --lua-dir=/usr/local/opt/lua@5.1 --tree=/private/tmp/neovim-20190515-46477-mw9nvr/deps-build
==> luarocks make --lua-dir=/usr/local/opt/lua@5.1 --tree=/private/tmp/neovim-20190515-46477-mw9nvr/deps-build
==> luarocks make --lua-dir=/usr/local/opt/lua@5.1 --tree=/private/tmp/neovim-20190515-46477-mw9nvr/deps-build
==> luarocks make --lua-dir=/usr/local/opt/lua@5.1 --tree=/private/tmp/neovim-20190515-46477-mw9nvr/deps-build
==> luarocks make --lua-dir=/usr/local/opt/lua@5.1 --tree=/private/tmp/neovim-20190515-46477-mw9nvr/deps-build
==> luarocks make --lua-dir=/usr/local/opt/lua@5.1 --tree=/private/tmp/neovim-20190515-46477-mw9nvr/deps-build
==> luarocks make --lua-dir=/usr/local/opt/lua@5.1 --tree=/private/tmp/neovim-20190515-46477-mw9nvr/deps-build
==> luarocks make --lua-dir=/usr/local/opt/lua@5.1 --tree=/private/tmp/neovim-20190515-46477-mw9nvr/deps-build
==> luarocks make --lua-dir=/usr/local/opt/lua@5.1 --tree=/private/tmp/neovim-20190515-46477-mw9nvr/deps-build
Last 15 lines from /Users/machupicchubeta/Library/Logs/Homebrew/neovim/16.luarocks:
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/uv.dir/deps/libuv/src/unix/dl.c.o] Error 1
make[2]: *** [CMakeFiles/uv.dir/deps/libuv/src/unix/getaddrinfo.c.o] Error 1
make[2]: *** [CMakeFiles/uv.dir/deps/libuv/src/unix/loop.c.o] Error 1
make[2]: *** [CMakeFiles/uv.dir/deps/libuv/src/threadpool.c.o] Error 1
make[2]: *** [CMakeFiles/uv.dir/deps/libuv/src/unix/async.c.o] Error 1
2 errors generated.
make[2]: *** [CMakeFiles/uv.dir/deps/libuv/src/unix/fs.c.o] Error 1
2 errors generated.
make[2]: *** [CMakeFiles/uv.dir/deps/libuv/src/unix/core.c.o] Error 1
make[1]: *** [CMakeFiles/uv.dir/all] Error 2
make: *** [all] Error 2

Error: Build error: Failed building.

READ THIS: https://docs.brew.sh/Troubleshooting
```