Stop to use "bench" command which cannot be installed due to an error
Error was:
```
$ brew install bench

Error: bench: no bottle available!
You can try to install from source with:
  brew install --build-from-source bench
Please note building from source is unsupported. You will encounter build
failures with some formulae. If you experience any issues please create pull
requests instead of asking for help on Homebrew's GitHub, Twitter or any other
official channels.
```