Follows renaming firefox-developer-edition to firefox@developer-edition
```
$ brew info --cask firefox-developer-edition

Warning: Cask homebrew/cask-versions/firefox-developer-edition was
renamed to firefox@developer-edition.
Error: Cask 'firefox-developer-edition' is unavailable: No Cask with
this name exists.
```

Refs.
- https://github.com/Homebrew/homebrew-cask/commit/34c9cd1149998376df6b20ad53ca3ba05d8fba00
- https://github.com/Homebrew/homebrew-cask/pull/172475
- https://github.com/Homebrew/homebrew-cask-versions/pull/20196