Change the order due to library dependency :metal:
`rbenv-default-gems` requires `rbenv`.
`rbenv` requires `ruby-build`.

Homebrew saild:
> Error: rbenv 1.1.1 is already installed
> To install HEAD, first run `brew unlink rbenv`

> Error: ruby-build 20170523 is already installed
> To install HEAD, first run `brew unlink ruby-build`