Soundflower is not supported on arm64 architecture
See also:
- https://github.com/mattingalls/Soundflower/tree/533a164f51295b9b1650f4798fca88c9458df222#readme
> M1 chip-based Macs are NOT YET SUPPORTED

Error was:
```
$ brew install --cask soundflower

==> Caveats
soundflower requires a kernel extension to work.
If the installation fails, retry after you enable it in:
  System Preferences → Security & Privacy → General

For more information, refer to vendor documentation or this Apple Technical Note:
  https://developer.apple.com/library/content/technotes/tn2459/_index.html

==> Downloading https://github.com/mattingalls/Soundflower/releases/download/2.0b2/Soundflower-2.0b2.dmg
==> Downloading from https://objects.githubusercontent.com/github-production-release-asset-2e65be/26034210/c0fdc2e0-86d1-11e4-853e-5e53e913b959?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz
######################################################################## 100.0%
==> Installing Cask soundflower
==> Running installer for soundflower; your password may be necessary.
Package installers may write to any location; options such as `--appdir` are ignored.
installer: Package name is Soundflower
installer: Installing at base path /
installer: The install failed. (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance. An error occurred while running scripts from the package “Soundflower.pkg”.)
==> Purging files for version 2.0b2 of Cask soundflower
Error: Failure while executing; `/usr/bin/sudo -E -- /usr/bin/env LOGNAME=machupicchubeta USER=machupicchubeta USERNAME=machupicchubeta /usr/sbin/installer -pkg /opt/homebrew/Caskroom/soundflower/2.0b2/Soundflower.pkg -target /` exited with 1. Here's the output:
installer: Package name is Soundflower
installer: Installing at base path /
installer: The install failed. (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance. An error occurred while running scripts from the package “Soundflower.pkg”.)
```