Install AdoptOpenJDK
Fix the Error:
```
sleuthkit: Java is required to install this formula.
Install AdoptOpenJDK with Homebrew Cask:
  brew cask install adoptopenjdk
Error: An unsatisfied requirement failed this build.
```