Introduce luarocks for neovim
Avoid neovim installation error.

Error was:
```
==> Upgrading neovim
Error: /usr/local/opt/luarocks not present or broken
Please reinstall luarocks. Sorry :(
```