No longer supported 'zoom-outlook-plugin' Cask on macOS newer than "Mojave"
Error was:
```
Error: This cask does not run on macOS versions newer than Mojave.
```