Unnecessary to install the 'microsoft-outlook' Cask separately
If I install 'microsoft-office' Cask, "Microsoft Outlook" app will also be installed.
I got a conflict error because I had already installed the 'microsoft-office' Cask.

Error was:
```
Error: Cask 'microsoft-outlook' conflicts with 'microsoft-office'.
```